/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RenewPlansRouteImport } from './routes/renew-plans'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MedicalIdsRouteImport } from './routes/medical-ids'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparePlansRouteImport } from './routes/compare-plans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesPersonalAlertDeviceSystemRouteImport } from './routes/guides.personal-alert-device-system'
import { Route as GuidesPersonal4gCareWatchRouteImport } from './routes/guides.personal-4g-care-watch'
import { Route as GuidesInHomeMedicalSystemRouteImport } from './routes/guides.in-home-medical-system'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewPlansRoute = RenewPlansRouteImport.update({
  id: '/renew-plans',
  path: '/renew-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalIdsRoute = MedicalIdsRouteImport.update({
  id: '/medical-ids',
  path: '/medical-ids',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePlansRoute = ComparePlansRouteImport.update({
  id: '/compare-plans',
  path: '/compare-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPersonalAlertDeviceSystemRoute =
  GuidesPersonalAlertDeviceSystemRouteImport.update({
    id: '/guides/personal-alert-device-system',
    path: '/guides/personal-alert-device-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesPersonal4gCareWatchRoute =
  GuidesPersonal4gCareWatchRouteImport.update({
    id: '/guides/personal-4g-care-watch',
    path: '/guides/personal-4g-care-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesInHomeMedicalSystemRoute =
  GuidesInHomeMedicalSystemRouteImport.update({
    id: '/guides/in-home-medical-system',
    path: '/guides/in-home-medical-system',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare-plans': typeof ComparePlansRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/medical-ids': typeof MedicalIdsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programs': typeof ProgramsRoute
  '/protection': typeof ProtectionRoute
  '/renew-plans': typeof RenewPlansRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/guides/in-home-medical-system': typeof GuidesInHomeMedicalSystemRoute
  '/guides/personal-4g-care-watch': typeof GuidesPersonal4gCareWatchRoute
  '/guides/personal-alert-device-system': typeof GuidesPersonalAlertDeviceSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare-plans': typeof ComparePlansRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/medical-ids': typeof MedicalIdsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programs': typeof ProgramsRoute
  '/protection': typeof ProtectionRoute
  '/renew-plans': typeof RenewPlansRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/guides/in-home-medical-system': typeof GuidesInHomeMedicalSystemRoute
  '/guides/personal-4g-care-watch': typeof GuidesPersonal4gCareWatchRoute
  '/guides/personal-alert-device-system': typeof GuidesPersonalAlertDeviceSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare-plans': typeof ComparePlansRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/medical-ids': typeof MedicalIdsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programs': typeof ProgramsRoute
  '/protection': typeof ProtectionRoute
  '/renew-plans': typeof RenewPlansRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/guides/in-home-medical-system': typeof GuidesInHomeMedicalSystemRoute
  '/guides/personal-4g-care-watch': typeof GuidesPersonal4gCareWatchRoute
  '/guides/personal-alert-device-system': typeof GuidesPersonalAlertDeviceSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare-plans'
    | '/contact'
    | '/how-it-works'
    | '/medical-ids'
    | '/privacy-policy'
    | '/programs'
    | '/protection'
    | '/renew-plans'
    | '/terms-of-service'
    | '/why-us'
    | '/guides/in-home-medical-system'
    | '/guides/personal-4g-care-watch'
    | '/guides/personal-alert-device-system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare-plans'
    | '/contact'
    | '/how-it-works'
    | '/medical-ids'
    | '/privacy-policy'
    | '/programs'
    | '/protection'
    | '/renew-plans'
    | '/terms-of-service'
    | '/why-us'
    | '/guides/in-home-medical-system'
    | '/guides/personal-4g-care-watch'
    | '/guides/personal-alert-device-system'
  id:
    | '__root__'
    | '/'
    | '/compare-plans'
    | '/contact'
    | '/how-it-works'
    | '/medical-ids'
    | '/privacy-policy'
    | '/programs'
    | '/protection'
    | '/renew-plans'
    | '/terms-of-service'
    | '/why-us'
    | '/guides/in-home-medical-system'
    | '/guides/personal-4g-care-watch'
    | '/guides/personal-alert-device-system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparePlansRoute: typeof ComparePlansRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MedicalIdsRoute: typeof MedicalIdsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProgramsRoute: typeof ProgramsRoute
  ProtectionRoute: typeof ProtectionRoute
  RenewPlansRoute: typeof RenewPlansRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhyUsRoute: typeof WhyUsRoute
  GuidesInHomeMedicalSystemRoute: typeof GuidesInHomeMedicalSystemRoute
  GuidesPersonal4gCareWatchRoute: typeof GuidesPersonal4gCareWatchRoute
  GuidesPersonalAlertDeviceSystemRoute: typeof GuidesPersonalAlertDeviceSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew-plans': {
      id: '/renew-plans'
      path: '/renew-plans'
      fullPath: '/renew-plans'
      preLoaderRoute: typeof RenewPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-ids': {
      id: '/medical-ids'
      path: '/medical-ids'
      fullPath: '/medical-ids'
      preLoaderRoute: typeof MedicalIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-plans': {
      id: '/compare-plans'
      path: '/compare-plans'
      fullPath: '/compare-plans'
      preLoaderRoute: typeof ComparePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/personal-alert-device-system': {
      id: '/guides/personal-alert-device-system'
      path: '/guides/personal-alert-device-system'
      fullPath: '/guides/personal-alert-device-system'
      preLoaderRoute: typeof GuidesPersonalAlertDeviceSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/personal-4g-care-watch': {
      id: '/guides/personal-4g-care-watch'
      path: '/guides/personal-4g-care-watch'
      fullPath: '/guides/personal-4g-care-watch'
      preLoaderRoute: typeof GuidesPersonal4gCareWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/in-home-medical-system': {
      id: '/guides/in-home-medical-system'
      path: '/guides/in-home-medical-system'
      fullPath: '/guides/in-home-medical-system'
      preLoaderRoute: typeof GuidesInHomeMedicalSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparePlansRoute: ComparePlansRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  MedicalIdsRoute: MedicalIdsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProgramsRoute: ProgramsRoute,
  ProtectionRoute: ProtectionRoute,
  RenewPlansRoute: RenewPlansRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhyUsRoute: WhyUsRoute,
  GuidesInHomeMedicalSystemRoute: GuidesInHomeMedicalSystemRoute,
  GuidesPersonal4gCareWatchRoute: GuidesPersonal4gCareWatchRoute,
  GuidesPersonalAlertDeviceSystemRoute: GuidesPersonalAlertDeviceSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
